"""Константы для моделей приложения reviews."""

CATEGORY_NAME_MAX_LENGTH = 256

CATEGORY_SLUG_MAX_LENGTH = 50

GENRE_NAME_MAX_LENGTH = 256

GENRE_SLUG_MAX_LENGTH = 50

TITLE_NAME_MAX_LENGTH = 256

TEXT_PREVIEW_LENGTH = 100

NAME_PREVIEW_LENGTH = 50
