[tool.black]
line-length = 79
skip-string-normalization = true

[tool.isort]
profile = "black"  
known_third_party = ["django", "requests"]  
known_first_party = ["api_yambd"] 
line_length = 79 
multi_line_output = 3
combine_as_imports = true 
order_by_type = true 