# Generated by Django 3.2 on 2024-12-31 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(
                error_messages={'unique': 'Поле email не уникально.'},
                max_length=254,
                unique=True,
                verbose_name='e-mail',
            ),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(
                error_messages={'unique': 'Поле username не уникально.'},
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Имя пользователя может содержать только буквы, цифры и символы @/./+/-/_ и не может быть "me"',
                        regex='^(?!me$)[\\w.@+-]+\\Z',
                    )
                ],
                verbose_name='Имя пользователя',
            ),
        ),
    ]
