# Generated by Django 3.2 on 2024-12-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(
                blank=True, null=True, verbose_name='Биография'
            ),
        ),
    ]
