# Generated by Django 3.2 on 2024-12-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name='Имя'
            ),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name='Фамилия'
            ),
        ),
    ]
